server:
  port: 8080
spring:
  application:
    name: rolin_reggie_take_out-master
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://124.71.65.12:13306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 6aad3d9cefc9e935
  redis:
    host: 124.71.65.12
    port: 7001
    password: 6aad3d9cefc9e935
    database: 0
  cache:
    type: redis
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间

mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: /root/reggie


#  server:
#    port: 8080
#  spring:
#    datasource:
##      url: jdbc:mysql://localhost:3306/springboottest
#      driver-class-name: com.mysql.cj.jdbc.Driver
#
#      url: jdbc:mysql://139.9.89.20/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#        username: root
#        password: root